spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  data:
    rest:
      base-path: /data-api
  security:
    oauth2:
      client:
        provider:
          tacocloud:
          issuer-uri: http://authserver:9000
          authorization-uri: http://authserver:9000/oauth2/authorize
          token-uri: http://authserver:9000/oauth2/token
          jwk-set-uri: http://authserver:9000/oauth2/jwks
          user-info-uri: http://authserver:9000/userinfo
          user-name-attribute: sub

      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks